/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_clock.h"
#include "fsl_lpi2c.h"
#include "fsl_gpt.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* BOARD_InitPeripherals defines for LPI2C1 */
/* Definition of peripheral ID */
#define LPI2C1_PERIPHERAL LPI2C1
/* Definition of clock source */
#define LPI2C1_CLOCK_FREQ 10000000UL
/* Transfer buffer size */
#define LPI2C1_MASTER_BUFFER_SIZE 40
/* Definition of follower address */
#define LPI2C1_MASTER_SLAVE_ADDRESS 0
/* Definition of peripheral ID */
#define GPT1_PERIPHERAL GPT1
/* Definition of the clock source frequency */
#define GPT1_CLOCK_SOURCE 62500000UL
/* GPT1 interrupt vector ID (number). */
#define GPT1_GPT_IRQN GPT1_IRQn
/* GPT1 interrupt handler identifier. */
#define GPT1_GPT_IRQHANDLER GPT1_IRQHandler

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const lpi2c_master_config_t LPI2C1_masterConfig;
extern lpi2c_master_transfer_t LPI2C1_masterTransfer;
extern uint8_t lpi2c1_master_buffer[LPI2C1_MASTER_BUFFER_SIZE];
extern lpi2c_master_handle_t lpi2c1_master_handle;
extern const gpt_config_t GPT1_config;

/***********************************************************************************************************************
 * Callback functions
 **********************************************************************************************************************/
/* Leader transfer callback function for component LPI2C1*/
extern void lpi2c1_master_callback(LPI2C_Type *base, lpi2c_master_handle_t *handle, status_t completionStatus, void *userData);

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
